from typing import Optional

SCHEMA_VERSION: int
__version__: str


class NativePlenoraError(Exception): ...


class NativeCancellationToken:
    def cancel(self) -> None: ...
    def is_cancelled(self) -> bool: ...


class NativeEngine:
    def __init__(self, config_json: Optional[str] = None) -> None: ...
    def execute(
        self,
        request_json: str,
        cancellation: Optional[NativeCancellationToken] = None,
    ) -> str: ...
    def capabilities(self) -> str: ...
    def open_cookie_session(self) -> str: ...
    def close_cookie_session(self, handle: str) -> None: ...
    def close(self) -> None: ...
    def is_closed(self) -> bool: ...
